### ISSUE TITLE
Categorization according to programming language.

### ISSUE THREAD

**Issue by Sddilora** [log101/YARP#10]
I believe projects should be categorized based on their programming languages, as this approach makes them more accessible.

**Comment by log101** [comment]
Well, one of my future goals is to make projects language-agnostic (excluding projects related to systems programming and similar niche fields). Because what we're aiming here is to teach programming "concepts" rather than languages. But we could change the way we categorize projects, for example concept based (frontend, backend etc). I wonder how would that be?

**Comment by Sddilora** [comment]
Since a part of the projects is intended for beginners, categorizing them as frontend and backend might be complex for beginners, in my opinion. And I don't want them to label themselves as frontend or backend developers, especially in the early stages. Yes, we are trying to teach the concepts, but after all, it will be more user-friendly for them to find languages and libraries they are familiar with under a single category. Moreover, the concepts are already present in our Readme file

**Comment by log101** [comment]
You could also think concepts as web, mobile, embedded etc. That wouldn't be complex even for beginners. Now there are two problems with language based categorization I can think of:
- How are we going to handle duplication, it would be hard to maintain if we crate a seperate page for each programming language. And if we put it on the same page, that's 2-3 copies of the same project on the same page. 
- It wouldn't be possible to see all projects in one page as some projects exists in one language but not in others. Furthermore there are projects that doesn't even related to any programming language such as "Kod Uçar Commit Kalır".

**Comment by Sddilora** [comment]
Perhaps we can categorize that section as 'Extras.' I'm not referring to the part in the README file where the names and difficulty levels of the projects are listed. We could organize that section ( projects/tr )  based on the programming language used (coding languages). However, it's not a major concern since the README file already indicates which language each project can be written in and provides direct links. Therefore, accessibility is already facilitated in this manner.

**Comment by log101** [comment]
Oh, I see. Yeah that's definitely possible, I didn't think people would browse the directories as everything is listed on Readme, but that definitely could be a case. It was hard to navigate the /projects/tr directory as there were lots of files with almost exactly the same way anyways.
I'll be updating the repo's directory structure according to languages this week, but would be glad if you could find time to do it.

**Comment by Sddilora** [comment]
of course I can, thanks for your consideration

**Comment by log101** [comment]
merged, thanks for the contribution!
